// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform ,kIsWeb,TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWsGZJTOT4ypcg5WdpIqwPB1iKRXvTyE',
    appId: '1:440547303494:web:bb9cd12042624727112a47',
    messagingSenderId: '440547303494',
    projectId: 'livchess-a71f4',
    authDomain: 'livchess-a71f4.firebaseapp.com',
    storageBucket: 'livchess-a71f4.firebasestorage.app',
    measurementId: 'G-P40CXNGV4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpw4aATahx7CWfxcRumUL5Uvtiiax3q7k',
    appId: '1:440547303494:android:016d7a7d93356444112a47',
    messagingSenderId: '440547303494',
    projectId: 'livchess-a71f4',
    storageBucket: 'livchess-a71f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY2pC1bNYFiCQNSRspX6-w9HWU1vFyOsk',
    appId: '1:440547303494:ios:d914c3f385a33d27112a47',
    messagingSenderId: '440547303494',
    projectId: 'livchess-a71f4',
    storageBucket: 'livchess-a71f4.firebasestorage.app',
    iosBundleId: 'com.example.livchess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY2pC1bNYFiCQNSRspX6-w9HWU1vFyOsk',
    appId: '1:440547303494:ios:d914c3f385a33d27112a47',
    messagingSenderId: '440547303494',
    projectId: 'livchess-a71f4',
    storageBucket: 'livchess-a71f4.firebasestorage.app',
    iosBundleId: 'com.example.livchess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAWsGZJTOT4ypcg5WdpIqwPB1iKRXvTyE',
    appId: '1:440547303494:web:191f90691da3e5ac112a47',
    messagingSenderId: '440547303494',
    projectId: 'livchess-a71f4',
    authDomain: 'livchess-a71f4.firebaseapp.com',
    storageBucket: 'livchess-a71f4.firebasestorage.app',
    measurementId: 'G-B6GM4FNJ2C',
  );

}